FROM node:14.17.6-alpine as build_stage

RUN mkdir -p /home/node/app
WORKDIR /home/node/app
COPY frontend/package.json .

# ENV REACT_APP_API=http://localhost:9999/index.php/wp-json
ENV REACT_APP_API=http://wordpress/index.php/wp-json

RUN yarn
COPY /frontend .

EXPOSE 3000

ENTRYPOINT ["yarn", "start"]