FROM node:13-alpine as build_stage

WORKDIR /app
COPY frontend/package.json .
COPY .env.frontend .env
RUN yarn
COPY /frontend/ .
RUN yarn build

FROM nginx:1.16.0-alpine

COPY --from=build_stage /app/build /usr/share/nginx/html

EXPOSE 80

ENTRYPOINT ["nginx", "-g", "daemon off;"]
