version: "3.1"
services:
  wordpress:
    container_name: histonline_wordpress
    image: wordpress:php7.3-fpm-alpine
    restart: always
    ports:
      - "${WORDPRESS_PORT}:80"
    environment:
    WORDPRESS_DB_HOST: db
    WORDPRESS_DB_USER: exampleuser
    WORDPRESS_DB_PASSWORD: examplepass
    WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html
  db:
    image:
    container_name: histonline_db
    ports:
      - "${MYSQL_PORT}:80"
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: dump_test
      MYSQL_USER: admin
      MYSQL_PASSWORD: "@5571992540736"
      MYSQL_ROOT_PASSWORD: "@5571992540736"
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - ./db_data:/var/lib/mysql
  frontend:
    container_name: histonline_frontend
    build:
        context: .
        dockerfile: Dockerfile.frontend
    restart: always
    volumes:
        - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
        - "${NGINX_PORT}:80"
    environment:
        NODE_ENV: production
